filter:
    excluded_paths:
        - 'tests/*'
        - 'features/*'

checks:
    php: true

build:
    image: default-bionic
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
    environment:
        variables:
            SYMFONY_DEPRECATIONS_HELPER: disabled
            SYMFONY_PHPUNIT_VERSION: 9.1
            XDEBUG_MODE: coverage
        php:
            version: 8.1.2
            ini:
                'date.timezone': 'Europe/London'
                memory_limit: -1
    tests:
        override:
            -   command: vendor/bin/simple-phpunit --coverage-clover=clover.xml
                coverage:
                    file: clover.xml
                    format: php-clover
